version: "3"
services:
  mysql:
    build: ./mysql
    container_name: spring_mysql
    env_file:
      - ./mysql/db.env
    volumes:
      - ./mysql/data:/var/lib/mysql #実データの永続化
      - ./mysql/log:/var/log/mysql #ログの永続化
    ports:
      - "3306:3306"

  dbclient:
    image: phpmyadmin/phpmyadmin
    container_name: dbclient
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=spring_mysql #MySQLのコンテナ名を指定
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - "4200:80"
    volumes:
      - ./dbclient/sessions:/sessions
    depends_on:
      - mysql

  java:
    image: openjdk:22
    container_name: java
    env_file:
      - ./mysql/db.env
    tty: true
    working_dir: /app
    volumes:
      - ../springboot:/app
    ports:
      - 8080:8080
      - 5050:5050
    depends_on:
      - mysql